spring:
  datasource:
    url: jdbc:postgresql://produccion_host:5432/event_management
    username: juan
    password: ""
    driver-class-name: org.postgresql.Driver
  logging:
    level:
      root: ERROR