spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_management
    username: juan
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true